# Generated by Django 5.1.4 on 2024-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_information_site_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
