# Generated by Django 5.1.4 on 2024-12-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_information_email_alter_information_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
