# Generated by Django 5.1.4 on 2024-12-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_visalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='visalist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
