# Generated by Django 5.1.4 on 2024-12-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_visalist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visalist',
            name='name',
        ),
        migrations.AddField(
            model_name='visalist',
            name='visa_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
