# Generated by Django 5.1.4 on 2024-12-21 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_packagelist_packagesilderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='sociallink',
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='app.information')),
            ],
        ),
    ]
